### ISSUE TITLE
Feature request: selectable orientation when you arrive at a photosphere

### ISSUE THREAD

**Issue by xyphoid** [IdeaSpaceVR/IdeaSpace#52]
I'm trying out the new photo tour theme. (which is very nice, I'd started doing my own mixed info / nav hotspot theme and this covers it completely) 

consider when you have 3 spheres linked to each other.  When you nav from A to C, you expect to be facing away from A. When you nav from B to C, you expect to be facing away from B. Right now, your orientation is just the default based on the sphere image, so it's jarring to navigate around in VR.

So it'd be nice to be able to specify a direction that your view is facing by default in each location. 

(I'm trying to do this myself but I've been running into issues with setting the yaw in webVR)

**Comment by weddingdj** [comment]
The next release of Ideaspace will have a rotation field type which allows you to set the default rotation of a photo sphere. I implemented this feature in the upcoming Photo Tour Pro theme, but I ran into issues as well if the theme is used in WebVR, because the rotation info from the HMD is overriding the manual settings, even if I set the initial rotation in a wrapper entity around the camera.
