### ISSUE TITLE
google cardboard on iPhone

### ISSUE THREAD

**Issue by bistek** [IdeaSpaceVR/IdeaSpace#68]
Hello, I'm looking for a web VR solution that works "everywhere", meaning with a browser on a PC or on a tablet (Android or iOs), on a phone with Google cardboard (both Android and iPhone), and on dedicated VR devices (Oculus, Viva, etc.), I was pretty excited when I found your project, but it appears it does non work on Google Cardboard / iPhone. This is common for many a-frame based applications, but not for all, and I still have not found why. Pleas let us know if you have a working solution!

Thanks!

**Comment by weddingdj** [comment]
Hello, 
Google Cardboard would use a timed trigger with a cursor which is in front of the camera. Other devices use external controllers. I found it hard to make it work in all devices, including Cardboard. So I made the decision to drop support for Cardboard since standalone VR devices will become very affordable and offer a much better experience than Cardboard. 

And iPhone based VR experiences are especially tricky since the latest Safari does not support sensor access by default anymore: https://github.com/aframevr/aframe/issues/3976 - so the user must manually enable flags in Safari in order to use Cardboard. This is a bad user experience.

**Comment by bistek** [comment]
The reason for using cardboard in educational projects is that you can set up a classroom for less than 100 € (or $), and students can have a VR device at home for a few bucks, and this has a potential to make VR incredibly popular. I hope you might see the opportunity.

Regarding the Safari issue, I tried also Chrome, but there are still problems.

In general the problem is that, when seen in the classical browser mode on iPhone, rotation is allowed only horizontally, and in Cardboard mode (clicking on the cardboard icon) it is completely locked.

This happens also on standard A-Frame scenes. For instance...

This works: https://apps.npr.org/rockymountain-vr/

The "helloworld" example works when run from aframe.io server, but when I clone it on my server it does not: https://aframe.io/examples/showcase/helloworld/

This does not work: http://cms-aframe.web.cern.ch/

It looks like there is an issue if the scene is on a different server with respect to aframe.io. Is this possible in your experience?

Thanks very much!

**Comment by weddingdj** [comment]
If you clone it and run in on your server, I think you need a SSL certificate (https:// and not http:// ).

**Comment by bistek** [comment]
Yes. Actually the problem was just that. And the CERN site cited above does not work on the iPhone since it is on a http server (not https). It might be useful warning potential users that on iPhone (and possibly Android) you need:

- https

- activate "motion & orientation" in Safari settings

Thanks very much!
